/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import com.college.util.JDBCUtil;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author saurabh
 */
public class courseDetails extends javax.swing.JFrame {

       
    static String type="";
    static String unm="";
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement s1;
    String q;

    /**
     * Creates new form courseDetails
     */
    public courseDetails(String t,String u) {
         initComponents();
         type=t;
         unm=u;
        sets();    
            
         
                 try
        {
       con=JDBCUtil.getConnection();  }
        catch(Exception e)
        {
            
        }
         disp();
         setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Course Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 11, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Add New Course", "Update", "Delete", "Choose Your Course" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 47, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Branch");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 169, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 168, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Tution Fee");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 169, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 168, 150, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Library Fee");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 199, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 198, 150, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Student Council Fee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 199, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 198, 150, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Other Fee");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 230, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 229, 150, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 85, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Total Fee");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 230, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 229, 150, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Calculate Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 267, -1, -1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 340, -1, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setText("Add New Course");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 340, -1, -1));

        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Course Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 112, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 111, 100, -1));

        jButton5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Course Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 86, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1359726.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        new frmAdmin(type,unm);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        sets();
        jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");jTextField4.setText("");jTextField5.setText("");jTextField6.setText("");
            
        String t = (String) jComboBox1.getSelectedItem();
        
        if(t.equals("") || t.equals("Choose Your Course"))
        {
            JOptionPane.showMessageDialog(this,"Choose Relevant Option, Or choose course name", "",JOptionPane.ERROR_MESSAGE);
                   new courseDetails(type,unm);
        }
        
        
        else if(t.equals("Select"))
        {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");jTextField4.setText("");jTextField5.setText("");jTextField6.setText("");
            
        }
        
        else if(t.equals("Add New Course"))
        {
            jLabel8.setVisible(true);
            jTextField7.setVisible(true);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("1000");jTextField4.setText("500");jTextField5.setText("500");jTextField6.setText("");
            jButton1.setVisible(true);jButton3.setVisible(true);
            jTextField1.setEditable(true);jTextField2.setEditable(true);jTextField3.setEditable(true);
            jTextField4.setEditable(true);jTextField5.setEditable(true);
        }
        
        else if(t.equals("Delete"))
        {
           jLabel9.setVisible(true);
           jComboBox2.setVisible(true);
           jButton5.setVisible(true);
            
        }
        
        else if(t.equals("Update"))
        {
           jLabel9.setVisible(true);
           jComboBox2.setVisible(true);
           jButton2.setVisible(true);    jButton1.setVisible(true);
           jTextField1.setEditable(true);jTextField2.setEditable(true);jTextField3.setEditable(true);
            jTextField4.setEditable(true);jTextField5.setEditable(true);
        }
        else{
         try
        {
        ps = con.prepareStatement("select * from course where name='"+t+"'");
        rs = ps.executeQuery();
        
        if(rs.next())
        {
            jTextField1.setText(rs.getString(2));
            jTextField2.setText(rs.getString(3));
            jTextField3.setText(rs.getString(4));
            jTextField4.setText(rs.getString(5));
            jTextField5.setText(rs.getString(6));
            jTextField6.setText(rs.getString(7));
            
          
        }
        
        }
        catch(Exception e)
        {}}
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String a = jTextField7.getText();String b = jTextField1.getText();String c = jTextField2.getText();
        String d = jTextField3.getText();String e = jTextField4.getText();String f = jTextField5.getText();
        String g = jTextField6.getText();
        
        if(a.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Course Name", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(b.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Branch Name", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(g.equals(""))
        {JOptionPane.showMessageDialog(this,"Calculate Total", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        
        try
        {
        q = "insert into course values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"')";
        s1 = con.createStatement();
        s1.executeUpdate(q);
        JOptionPane.showMessageDialog(this,"Added Successfully", "",JOptionPane.PLAIN_MESSAGE);
                   new frmAdmin(type,unm);
                   this.dispose();
        }
        catch(Exception e2)
        {}
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String c = jTextField2.getText();
        String d = jTextField3.getText();
        String e = jTextField4.getText();
        String f = jTextField5.getText();
        
        if(c.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Tution Fee", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(d.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Library Fee", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(e.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Student Council Fee", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(f.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Other Fee", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        int total = Integer.parseInt(c)+Integer.parseInt(e)+Integer.parseInt(d)+Integer.parseInt(f) ;
        jTextField6.setText(Integer.toString(total));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String a =(String)jComboBox2.getSelectedItem();
        
        if(a.equals(""))
        {JOptionPane.showMessageDialog(this,"Select name to delete", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        
        try
        {
        q = "delete from course where name='"+a+"'";
        s1 = con.createStatement();
        s1.executeUpdate(q);
        JOptionPane.showMessageDialog(this,"Deleted Successfully", "",JOptionPane.PLAIN_MESSAGE);
                   new frmAdmin(type,unm);
                   this.dispose();
        }
        catch(Exception e){}
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
             String a =(String)jComboBox2.getSelectedItem();
             try
             {
                 ps = con.prepareStatement("select * from course where name='"+a+"'");
        rs = ps.executeQuery();
        
        if(rs.next())
        {
            System.out.println("saurabh garg");
            jTextField1.setText(rs.getString(2));
            jTextField2.setText(rs.getString(3));
            jTextField3.setText(rs.getString(4));
            jTextField4.setText(rs.getString(5));
            jTextField5.setText(rs.getString(6));
            jTextField6.setText(rs.getString(7));
            
          
        }
             }catch(Exception e){}
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String a = (String)jComboBox2.getSelectedItem();String b = jTextField1.getText();String c = jTextField2.getText();
        String d = jTextField3.getText();String e = jTextField4.getText();String f = jTextField5.getText();
        String g = jTextField6.getText();
        
        
        if(b.equals(""))
        {JOptionPane.showMessageDialog(this,"Enter Branch Name", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        if(g.equals(""))
        {JOptionPane.showMessageDialog(this,"Calculate Total", "",JOptionPane.ERROR_MESSAGE);
                   return;                   }
        
        try
        {
        q = "update course set branch='"+b+"',tutionfee='"+c+"',libraryfee='"+d+"',studentCouncilFee='"+e+"',otherFee='"+f+"',totalFee='"+g+"' where name='"+a+"'";
        s1 = con.createStatement();
        s1.executeUpdate(q);
        JOptionPane.showMessageDialog(this,"Updated Successfully", "",JOptionPane.PLAIN_MESSAGE);
                   new frmAdmin(type,unm);
                   this.dispose();
        }
        catch(Exception e2)
        {}
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                new courseDetails(type,unm);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void disp() {
     
        
        try
        {
        ps = con.prepareStatement("select * from course");
        
        rs = ps.executeQuery();
        
        while(rs.next())
        {
            String e = rs.getString(1);
            jComboBox1.addItem(e);
            jComboBox2.addItem(e);
        }

        }
        catch(Exception e)
        {
                        
        }
    }

    private void sets() {
         jComboBox2.setVisible(false);
         jLabel8.setVisible(false);
         jLabel9.setVisible(false);
         jTextField7.setVisible(false);
         jButton1.setVisible(false);
         jButton2.setVisible(false);
         jButton3.setVisible(false);
         jButton5.setVisible(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jTextField4.setEditable(false);jTextField5.setEditable(false);jTextField6.setEditable(false);
        
    }
}

