/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import com.college.util.JDBCUtil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author saurabh
 */
public class registration extends javax.swing.JFrame {

    static String type = "";
    static String unm = "";
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement s1;
    String q;

    /**
     * Creates new form registration
     */
    public registration(String t, String u) {
        initComponents();
        type = t;
        unm = u;
        try {
          con=JDBCUtil.getConnection(); 
          } catch (Exception ez) {
        }


        set_begin();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField22 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 69, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 68, 120, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Enrollment Number ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 107, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 106, 120, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Last Enroll");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 144, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 144, 100, 16));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("12th Roll Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 221, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 217, 120, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("All Documents verified");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 265, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Contact Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 311, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 310, 120, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 348, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 462, 120, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("City");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 463, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("District");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 501, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("State");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 535, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setText("Pincode");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 573, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Email ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 338, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Father's/Guardian Name");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 262, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Mother's name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 300, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 500, 120, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 534, 120, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 572, 120, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 261, 120, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 299, 120, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 337, 120, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 375, 120, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Parent's Email");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 376, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 217, -1, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Parents Contact");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 414, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 217, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Gender");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 348, -1, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 413, 120, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Hostel");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 218, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("Bus");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 218, -1, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setText("Applicable For Any Scholarship");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 69, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Scholarship Name");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setText("Scholarship Amount");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 120, -1));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel26.setText("Hostel Name");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 69, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 68, -1, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setText("Seats Left");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 145, -1, -1));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 107, 120, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setText("Fee");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 106, -1, -1));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 144, 120, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel29.setText("Bus Number");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 218, -1, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setText("Fee");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 256, -1, -1));
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 255, 120, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel31.setText("Seats left");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 294, -1, -1));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 293, 120, -1));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel32.setText("Course");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 344, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 343, -1, -1));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 386, 120, -1));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel33.setText("Fee");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 387, -1, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setText("Total Fee");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 425, -1, -1));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 424, 120, -1));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel35.setText("Payment Method");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Cheque", "Draft" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setText("Bank Name");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 120, -1));

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel37.setText("Number");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, -1, -1));
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 120, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 470, -1, -1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 515, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes" }));
        getContentPane().add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jButton3.setText("Calculate Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1359726.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
jTextField23.setText("");
        String df = (String) jComboBox1.getSelectedItem();

        if (df.equals("Yes")) {
            jLabel26.setVisible(true);
            jLabel27.setVisible(true);
            jLabel28.setVisible(true);
            jComboBox4.setVisible(true);
            jTextField17.setVisible(true);
            jTextField18.setVisible(true);
        } else {
            jLabel26.setVisible(false);
            jLabel27.setVisible(false);
            jLabel28.setVisible(false);
            jComboBox4.setVisible(false);
            jTextField17.setVisible(false);
            jTextField18.setVisible(false);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
jTextField23.setText("");        String dg = (String) jComboBox2.getSelectedItem();

        if (dg.equals("Yes")) {
            jLabel29.setVisible(true);
            jLabel30.setVisible(true);
            jLabel31.setVisible(true);
            jComboBox8.setVisible(true);
            jTextField20.setVisible(true);
            jTextField21.setVisible(true);
        } else {
            jLabel29.setVisible(false);
            jLabel30.setVisible(false);
            jLabel31.setVisible(false);
            jComboBox8.setVisible(false);
            jTextField20.setVisible(false);
            jTextField21.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String dj = (String) jComboBox3.getSelectedItem();
        jTextField23.setText("");

        if (dj.equals("Yes")) {
            jLabel24.setVisible(true);
            jLabel25.setVisible(true);
            jComboBox9.setVisible(true);
            jTextField16.setVisible(true);
        } else {
            jLabel24.setVisible(false);
            jLabel25.setVisible(false);
            jComboBox9.setVisible(false);
            jTextField16.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new frmAdmin(type, unm);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nm = jTextField1.getText();
        if (nm.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Name", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String en = jTextField2.getText();
        if (en.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Enroll Number", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int y = 0;
            ps = con.prepareStatement("select * from studInfo where enroll='" + en + "'");
            rs = ps.executeQuery();
            while (rs.next()) {
                y = 1;
            }
            if (y == 1) {
                JOptionPane.showMessageDialog(this, "Enroll Number must be unique", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
        }

        String gen = (String) jComboBox10.getSelectedItem();

        String rn = jTextField4.getText();
        if (rn.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter 12th Roll Number", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String no = jTextField5.getText();
        if (no.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Contact Number", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String add = jTextArea1.getText();
        if (add.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Address", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String city = jTextField6.getText();
        if (city.equals("")) {
            JOptionPane.showMessageDialog(this, "City cannot be empty", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String dist = jTextField7.getText();
        String pin = jTextField9.getText();
        String state = jTextField8.getText();
        if (state.equals("")) {
            JOptionPane.showMessageDialog(this, "State cannot be empty", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String em = jTextField12.getText();
        if (em.equals("")) {
            JOptionPane.showMessageDialog(this, "Email Id cannot be empty", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String mn = jTextField11.getText();
        String fn = jTextField10.getText();
        if (fn.equals("")) {
            JOptionPane.showMessageDialog(this, "Fathers name cannot be empty", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

       String pn = jTextField14.getText();
        if (pn.equals("")) {
            JOptionPane.showMessageDialog(this, "Contact Number cannot be empty", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pe = jTextField13.getText();
        String doc = (String)jComboBox11.getSelectedItem();
        String sch = (String) jComboBox3.getSelectedItem();
        String sch1 = (String) jComboBox9.getSelectedItem();
        String sch2 = jTextField16.getText();
        if (sch.equals("Yes")) {
            if (sch1.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Scholarship Name must be selected", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String hos = (String) jComboBox1.getSelectedItem();
        String hos1 = (String) jComboBox4.getSelectedItem();
        String hos2 = jTextField17.getText();
        String hos3 = jTextField18.getText();

        if (hos.equals("Yes")) {
            if (hos1.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Hostel Name must be selected", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String bus = (String) jComboBox2.getSelectedItem();
        
        String bus1 = (String) jComboBox8.getSelectedItem();
        String bus2 = jTextField20.getText();
        String bus3 = jTextField21.getText();

        if (bus.equals("Yes")) {
            if (bus1.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Bus number must be selected", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        String cr = (String) jComboBox5.getSelectedItem();
        String cr1 = jTextField22.getText();
        String cr2 = jTextField23.getText();
        if (cr.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Course must be selected", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        if(cr2.equals("")){JOptionPane.showMessageDialog(this, "Total must be calculated", "", JOptionPane.ERROR_MESSAGE);
                return;}
        
        
        String fp1 = (String) jComboBox6.getSelectedItem();
        String fp2 = jTextField25.getText();String fp3 = jTextField24.getText();
        
            if (fp1.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Payment Mode must be selected", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (fp2.equals("")) {
                JOptionPane.showMessageDialog(this, "Payment Number Must be entered", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (fp3.equals("")) {
                JOptionPane.showMessageDialog(this, "Bank name must be entered", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
     String gh = "Student";
        
        
        q  = "insert into studinfo values('"+nm+"','"+en+"','"+no+"','"+add+"','"+city+"','"+dist+"','"+state+"','"+pin+"','"+em+"','"+fn+"','"+mn+"','"+pn+"','"+pe+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       System.out.println("query 1"); 
       String gg="Yes";
       q = "insert into studinfo1 values('"+gen+"','"+rn+"','"+doc+"','"+sch+"','"+bus+"','"+hos+"','"+gg+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       System.out.println("query 2"); 
       
       if (sch.equals("Yes"))
       {q = "insert into stud_scholar values('"+en+"','"+sch1+"','"+sch2+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       }
       System.out.println("query 3"); 
       if (hos.equals("Yes"))
       {q = "insert into stud_hos values('"+en+"','"+hos1+"','"+hos2+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       }System.out.println("query 4"); 
       if (bus.equals("Yes"))
       {q = "insert into stud_bus values('"+en+"','"+bus2+"','"+bus1+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       }System.out.println("query 5"); 
     
     q = "insert into stud_crs_fee values('"+en+"','"+cr+"','"+cr1+"','"+cr2+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
     System.out.println("query 6");
     
       
       q = "insert into stud_pay_mode values('"+en+"','"+fp1+"','"+fp2+"','"+fp3+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       System.out.println("query 7"); 
       
       q = "insert into login values('"+gh+"','"+nm+"','"+en+"','"+en+"')";
       try{ s1 = con.createStatement();
        s1.executeUpdate(q);}catch(Exception er){}
       
       
       JOptionPane.showMessageDialog(this," Registered Successfully","",
                    JOptionPane.PLAIN_MESSAGE); 
       new frmAdmin(type,unm);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
jTextField23.setText("");
        String ff = (String) jComboBox9.getSelectedItem();
        if (ff.equals("Select")) {
            jTextField16.setText("");
        } else {
            System.out.println("in");
            try {
                ps = con.prepareStatement("select * from scholarship where name='" + ff + "'");
                rs = ps.executeQuery();
                if (rs.next()) {
                    jTextField16.setText(rs.getString(2));
                }
            } catch (Exception e) {
            }
            System.out.println("out");
        }
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        jTextField23.setText("");
        String ff = (String) jComboBox4.getSelectedItem();
        if (ff.equals("Select")) {
            jTextField17.setText("");
            jTextField18.setText("");
        } else {
            System.out.println("in");
            try {
                ps = con.prepareStatement("select * from hostel where name='" + ff + "'");
                rs = ps.executeQuery();
                if (rs.next()) {
                    jTextField17.setText(rs.getString(2));
                    jTextField18.setText(rs.getString(3));
                }
            } catch (Exception e) {
            }
            System.out.println("out");
        }

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
jTextField23.setText("");
                String ff = (String) jComboBox8.getSelectedItem();
        if (ff.equals("Select")) {
            jTextField20.setText("");
            jTextField21.setText("");
        } else {
            System.out.println("in");
            try {
                ps = con.prepareStatement("select * from bus where num='" + ff + "'");
                rs = ps.executeQuery();
                if (rs.next()) {
                    jTextField20.setText(rs.getString(2));
                    jTextField21.setText(rs.getString(3));
                }
            } catch (Exception e) {
            }
            System.out.println("out");
        }

        
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        
                String ff = (String) jComboBox5.getSelectedItem();
        if (ff.equals("Select")) {
            jTextField22.setText("");
            jTextField23.setText("");
        } else {
            System.out.println("in");
            
            try {
                ps = con.prepareStatement("select * from course where name='" + ff + "'");
                rs = ps.executeQuery();
                if (rs.next()) {
                   String m =  rs.getString(7);
                    jTextField22.setText(m);
                
                }
            } catch (Exception e) {
            }
            System.out.println("out");
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        String ff = (String) jComboBox5.getSelectedItem();
        if (ff.equals("Select")) {
            JOptionPane.showMessageDialog(this," Select Course Name","",
                    JOptionPane.ERROR_MESSAGE);return;
        }
        
        int total =0;
        String m = jTextField22.getText();           
        String sch = (String) jComboBox3.getSelectedItem();
                    String hos = (String) jComboBox1.getSelectedItem();        
                     String bus = (String) jComboBox2.getSelectedItem(); 
                    
                     String sch1 = (String)jComboBox9.getSelectedItem();
                     String hos1 = (String)jComboBox4.getSelectedItem();
                     String bus1 = (String)jComboBox8.getSelectedItem();
                     
                     String sch2 = jTextField16.getText();String hos2 = jTextField17.getText();
                        String bus2 = jTextField20.getText();
                        
                        total = total + Integer.parseInt(m);
                        if(hos.equals("Yes"))
                        {
                            if(hos1.equals("Select"))
                            {JOptionPane.showMessageDialog(this," Select Hostel Name","",
                    JOptionPane.ERROR_MESSAGE);return;}
                            else
                            total = total + Integer.parseInt(hos2);
                        }
                        
                        if(bus.equals("Yes"))
                        {
                            if(bus1.equals("Select"))
                            {JOptionPane.showMessageDialog(this," Select Bus Number","",
                    JOptionPane.ERROR_MESSAGE);return;}
                            else
                            total = total + Integer.parseInt(bus2);
                        }
                        if(sch.equals("Yes"))
                        {
                            if(sch1.equals("Select"))
                            {JOptionPane.showMessageDialog(this," Select Scholarship Name","",
                    JOptionPane.ERROR_MESSAGE);return;}
                            else
                            total = total - Integer.parseInt(sch2);
                        }   
                        jTextField23.setText(Integer.toString(total));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        
        String pp = (String)jComboBox6.getSelectedItem();
        
        if(pp.equals("Select"))
        {
            jTextField24.setText("");jTextField25.setText("");
        }
        
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new registration(type, unm);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void set_begin() {
        jTextField16.setEditable(false);
        jTextField17.setEditable(false);
        jTextField18.setEditable(false);
          jTextField20.setEditable(false);jTextField21.setEditable(false);
        jTextField22.setEditable(false);
        jTextField23.setEditable(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        jComboBox4.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        jLabel31.setVisible(false);
        jComboBox8.setVisible(false);
        jTextField20.setVisible(false);
        jTextField21.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jComboBox9.setVisible(false);
        jTextField16.setVisible(false);
        try {
            ps = con.prepareStatement("select * from login where type='Student' ORDER BY username");
            rs = ps.executeQuery();
            while (rs.next()) {
                q = rs.getString(3);
            }
            jLabel5.setText(q);

            ps = con.prepareStatement("select * from scholarship");
            rs = ps.executeQuery();
            while (rs.next()) {
                String hg = rs.getString(1);
                jComboBox9.addItem(hg);
            }

            ps = con.prepareStatement("select * from hostel");
            rs = ps.executeQuery();
            while (rs.next()) {
                String hg = rs.getString(1);
                jComboBox4.addItem(hg);
            }
            
            ps = con.prepareStatement("select * from bus");
            rs = ps.executeQuery();
            while (rs.next()) {
                String hg = rs.getString(1);
                jComboBox8.addItem(hg);
            }

            ps = con.prepareStatement("select * from course");
            rs = ps.executeQuery();
            while (rs.next()) {
                String hg = rs.getString(1);
                jComboBox5.addItem(hg);
            }

        } catch (Exception rf) {
        }




    }
}
