/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import com.college.util.JDBCUtil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author saurabh
 */
public class studProfile extends javax.swing.JFrame {
    static String type="";
    static String unm="";
            Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement sq;
    String q,q1;
    int x_c=0;

    /**
     * Creates new form studProfile
     */
    public studProfile(String t,String u) {
        
        initComponents();
        type=t;
        unm=u;
        try
        {
        con = JDBCUtil.getConnection();
	
        }
        catch(Exception e)
        {
            
        }
        jTextField2.setText(unm);
        check();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Student Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 48, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Enrollment Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 110, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 78, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 109, 100, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Contact Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Contact Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 173, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 172, 100, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 245, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("City");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 175, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("District");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 213, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("State");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 251, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("PinCode");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 289, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 174, 100, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 212, 100, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 250, 100, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 288, 100, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Parent/Guardian Information");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Email ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 339, 200, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Father's/Guardian's Name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 419, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setText("Mother's Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 457, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Contact NO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 419, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Email ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 457, -1, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 418, 150, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 456, 150, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 418, 150, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 456, 150, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 535, -1, -1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 535, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 47, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 79, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1359726.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new frmAdmin(type,unm);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        String t = (String)jComboBox1.getSelectedItem();
        
        if(t.equals("Select"))
        {
            jTextArea1.setText("");
            jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText("");
            jTextField5.setText("");jTextField6.setText("");jTextField7.setText("");jTextField8.setText("");
            jTextField9.setText("");jTextField10.setText("");jTextField11.setText("");jTextField12.setText("");
            
        }
        else
        {
            try
            {
            ps = con.prepareStatement("select * from studInfo where name='"+t+"'");
            rs = ps.executeQuery();
            if(rs.next())
            {
                jTextField2.setText(rs.getString(2));jTextField3.setText(rs.getString(3));jTextField4.setText(rs.getString(5));
                jTextField5.setText(rs.getString(6));jTextField6.setText(rs.getString(7));jTextField7.setText(rs.getString(8));
                jTextField8.setText(rs.getString(9));jTextField9.setText(rs.getString(10));jTextField10.setText(rs.getString(11));
                jTextField11.setText(rs.getString(12));jTextField12.setText(rs.getString(13));
                jTextArea1.setText(rs.getString(4));
            }
            }catch(Exception e){}
           
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String s1 = jTextField1.getText();String s2 = jTextField2.getText();String s3 = jTextField3.getText();
        String s5 = jTextField4.getText();String s6 = jTextField5.getText();String s7 = jTextField6.getText();
        String s8 = jTextField7.getText();String s9 = jTextField8.getText();String s10 = jTextField9.getText();
        String s11 = jTextField10.getText();String s12 = jTextField11.getText();String s13 = jTextField12.getText();
        String s4 = jTextArea1.getText();
        
        if(s1.equals(""))
        {JOptionPane.showMessageDialog(this,"Name cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s2.equals(""))
        {JOptionPane.showMessageDialog(this,"Enroll cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s3.equals(""))
        {JOptionPane.showMessageDialog(this,"Contact Number cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s4.equals(""))
        {JOptionPane.showMessageDialog(this,"Address cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s5.equals(""))
        {JOptionPane.showMessageDialog(this,"City cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        
        if(s7.equals(""))
        {JOptionPane.showMessageDialog(this,"State cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s9.equals(""))
        {JOptionPane.showMessageDialog(this,"Email Id cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        if(s10.equals(""))
        {JOptionPane.showMessageDialog(this,"Fathers name cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        
        if(s12.equals(""))
        {JOptionPane.showMessageDialog(this,"Contact Number cannot be empty", "",JOptionPane.ERROR_MESSAGE);return;}
        
        
        try
        {
        q = "update studInfo set name='"+s1+"',stud_contact='"+s3+"',address='"+s4+"',city='"+s5+"',district='"+s6+"',state='"+s7+"',pincode='"+s8+"',stud_email='"+s9+"',father='"+s10+"',mother='"+s11+"',contact='"+s12+"',email='"+s13+"' where enroll='"+s2+"'";
        q1 ="insert into studInfo values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"','"+s13+"')";
        sq = con.createStatement();
        if(x_c == 0)
        {
        sq.executeUpdate(q);
        JOptionPane.showMessageDialog(this," Updated Successfully", "",
                    JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
        sq.executeUpdate(q1);
        JOptionPane.showMessageDialog(this," Inserted Successfully", "",
                    JOptionPane.PLAIN_MESSAGE);}new frmAdmin(type,unm);this.dispose();
        }catch(Exception em){}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studProfile(type,unm);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void check() {
        jTextField2.setEditable(false);
        jTextField2.setText("");
        System.out.println(type);
        if(type.equals("Admin") || type.equals("Employee"))
        {System.out.println("Inside student admin query");
            jTextField1.setVisible(false);
            jTextField2.setText("");
            jLabel17.setVisible(false);
            jButton1.setVisible(false);
            jTextField2.setEditable(false);jTextField3.setEditable(false);jTextField4.setEditable(false);
            jTextField5.setEditable(false);jTextField6.setEditable(false);jTextField7.setEditable(false);
            jTextField8.setEditable(false);jTextField9.setEditable(false);jTextField10.setEditable(false);
            jTextField11.setEditable(false);jTextField12.setEditable(false);
            jTextArea1.setEditable(false);
        try
        {
        ps = con.prepareStatement("select * from studInfo");
        rs = ps.executeQuery();
        
        while(rs.next())
        {
            System.out.println("a");
            String e = rs.getString(1);
            jComboBox1.addItem(e);
        }}
        catch(Exception e){}
            
            
        }
        
        if(type.equals("Student"))
        {
            jLabel2.setVisible(false);
            jComboBox1.setVisible(false);
            jTextField2.setEditable(false);
            try
            {
            
            System.out.println("In");
            ps = con.prepareStatement("select * from studInfo where enroll='"+unm+"'");
            rs = ps.executeQuery();
            if(rs.next())
            {System.out.println("Inside student query");
                jTextField1.setText(rs.getString(1));
            jTextField2.setText(unm);
                jTextField3.setText(rs.getString(3));jTextField4.setText(rs.getString(5));
                jTextField5.setText(rs.getString(6));jTextField6.setText(rs.getString(7));jTextField7.setText(rs.getString(8));
                jTextField8.setText(rs.getString(9));jTextField9.setText(rs.getString(10));jTextField10.setText(rs.getString(11));
                jTextField11.setText(rs.getString(12));jTextField12.setText(rs.getString(13));
                jTextArea1.setText(rs.getString(4));
            
            }
            else
            {
                 JOptionPane.showMessageDialog(this," No information available, Please Fill the information", "",
                    JOptionPane.PLAIN_MESSAGE); x_c =1;              
            }
            
            System.out.println("out");
            }catch(Exception e){}
            
        }
    }
}
